project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

execute:
  freeze: true

format:
  html:
    css: styles.css
    theme: slate
    code-copy: true

website:
  title: Advent of code
  sidebar:
    background: primary
    search: false
    style: docked
    tools:
      - icon: github
        href: https://github.com/meterds/adventofcode
    contents:
      - text: "Welcome"
        file: index.qmd
      - section: "2020"
      - section: "2021"
      - section: "2022"
      - section: "2023"
        contents: 2023/qmd/*
